-- Migration 003 — RECONCILED / NO-OP (P2.7)
-- This file originally defined `events` with an incompatible schema
-- (event_id, event_date, no status column). Migration 002 already created
-- the real `events` table with the correct shape:
--   id, cat, title, date, theme, description, suggested_menu, status,
--   created_at, updated_at
-- The CREATE TABLE IF NOT EXISTS below is intentionally removed so a
-- drop-and-replay cannot silently flip the schema and break routes/events.py.
-- The live schema on MJCCv1 (mgvyylvmkxhhataavqjz) matches 002, not this file.
--
-- DO NOT restore the old CREATE TABLE here.
SELECT 1; -- no-op placeholder
